export class Agent {
    agentid:string;
    username:string;
    passwordhash:string;
    email:string;
    emailconfirmed:Boolean;
    phonenumber:number;
    phonenumberconfirmed:Boolean;
    name:string;
    companyname:string;
    createdatetime:Date;
    roleid:number;
    city:string;
    state:string;
    landmark:string;
    pin:number;
    address:string;
    contactpersonname:string;
    contactpersonmobile:number;
    allocatedid:number;
}
